//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Pid { get; set; }
        public int Cid { get; set; }
        public int Eid { get; set; }
        public int Sid { get; set; }
        public int Aid { get; set; }
        public int Amount { get; set; }
        public string Dateofpayment { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Service Service { get; set; }
    }
}
